# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11aca9dd3b7054ce82acfba4cfd725c9ed830ab8e06b93065685d1389fe0c51f2cd37001ef2665fc0a6c21fc67504403d10536112ae41cd37a8e109458aac87e

test:
  secret_key_base: 1b8b181181f2f20c0989b9ffbb35cfdaceb4ab4df7f4f4f8f7fd1b0d31cbffa16333c94528b5a0ecb0da6f779f654961739b997af6d7056548a97f8395f37497

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
